[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_BUILDFUTURE = "true"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"

